version: 1
appendOnly: true
labels:
  - label: "bugfix"
    title: "(?i).*fix.*"
  - label: "bugfix"
    branch: "(?i).*fix.*"
  - label: "feature"
    title: "(?i).*feat.*"
  - label: "feature"
    branch: "(?i).*feat.*"
  - label: "breaking-change"
    title: "(?i).*breaking[ -_]change.*"
  - label: "breaking-change"
    branch: "(?i).*breaking[ -_]change.*"
  - label: "github_actions"
    title: "(?i).*github[ -_]action.*"
  - label: "github_actions"
    branch: "(?i).*github[ -_]action.*"
  - label: "enhancement"
    title: "(?i).*enhance.*"
  - label: "enhancement"
    branch: "(?i).*enhance.*"
  - label: "enhancement"
    title: "(?i).*improve.*"
  - label: "enhancement"
    branch: "(?i).*improve.*"
  - label: "documentation"
    title: "(?i).*document.*"
  - label: "documentation"
    branch: "(?i).*document.*"
  - label: "documentation"
    title: "(?i).*readme.*"
  - label: "documentation"
    branch: "(?i).*readme.*"
  - label: "code-quality"
    title: "(?i).*lint.*"
  - label: "code-quality"
    title: "(?i).*ruff.*"
  - label: "code-quality"
    title: "(?i).*mypy.*"
  - label: "code-quality"
    title: "(?i).*pre[ -_]commit.*"
