"""Core OPNsense client lifecycle, transport, and shared helpers."""

from .client_methods_part1 import (
    __init__,
    _do_get,
    _do_get_from_stream,
    _do_post,
    _exec_php,
    _extract_firmware_version_from_path,
    _get,
    _get_from_stream,
    _get_proxy,
    _monitor_queue,
    _post,
    _process_queue,
    _restore_config_section,
    _safe_dict_get,
    _safe_dict_post,
    _safe_list_get,
    get_host_firmware_version,
    get_query_counts,
    is_plugin_installed,
    name,
    reset_query_counts,
    set_use_snake_case,
)
from .client_methods_part2 import _filter_configure, _get_check, _safe_list_post
from .client_methods_part5 import async_close

__all__ = [
    "__init__",
    "name",
    "reset_query_counts",
    "get_query_counts",
    "_get_proxy",
    "_restore_config_section",
    "_exec_php",
    "get_host_firmware_version",
    "_extract_firmware_version_from_path",
    "set_use_snake_case",
    "is_plugin_installed",
    "_get_from_stream",
    "_get",
    "_post",
    "_process_queue",
    "_monitor_queue",
    "_do_get_from_stream",
    "_do_get",
    "_safe_dict_get",
    "_safe_list_get",
    "_do_post",
    "_safe_dict_post",
    "_safe_list_post",
    "_get_check",
    "_filter_configure",
    "async_close",
]
