name: Linters

on:
  pull_request:
  push:
    branches:
      - main

permissions:
  contents: read

jobs:
  linters:
    name: review
    runs-on: ubuntu-latest
    steps:
      - name: Checkout Repository
        uses: actions/checkout@v7
        with:
          ref: ${{ github.sha }}
          persist-credentials: false

      - name: Setup uv (with caching)
        uses: astral-sh/setup-uv@v10.1.0
        with:
          python-version: "3.14"
          enable-cache: true
          ignore-nothing-to-cache: true
          cache-dependency-glob: uv.lock

      - name: Run prek
        uses: j178/prek-action@v2
        env:
          UV_LOCKED: "1"
