name: prek Autoupdate

on:
  schedule:
    - cron: '47 7 * * *'
  workflow_dispatch:

jobs:
  prek-autoupdate:
    uses: Snuffy2/prek-autoupdate/.github/workflows/prek_autoupdate.yml@v1
    permissions:
      contents: write
      pull-requests: write
      actions: write
    with:
      update-day: "4"
      dispatch-workflows: |
        linters.yml
        pytest_coverage.yml
        validate.yml
