name: HA and HACS Validate

on:
  pull_request:
  workflow_dispatch:
  push:
    branches:
      - main
      - master

jobs:
  ha_validation:
    name: Hassfest Validation
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v5
      - name: Hassfest validation
        uses: home-assistant/actions/hassfest@master
  hacs_validation:
    name: HACS Validation
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v5
      - name: HACS validation
        uses: hacs/action@main
        with:
          category: integration
          ignore: brands
